name: amase
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - astropy
  - numpy
  - scipy
  - matplotlib
  - astroscrappy
  - joblib
  - numba
  - pytest
  - pip
  - pip:
    - -e .
