[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "amasedrp"
version = "0.1.0"
description = "Data reduction pipeline for the AMASE project."
authors = [
    {name = "Zeng Guangquan",email = "guangquan.zeng@outlook.com"}
]
dependencies = [
    "astropy",
    "numpy",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]